<?php
$pageTitle='Build Your Budget Plan';
$pageDescription='Tell Tin-Tin Trekking your budget, preferences and travel goals to receive a personalized Himalayan trek plan.';
require __DIR__.'/data/treks.php';
require __DIR__.'/includes/header.php';
$selectedTrek=$_GET['trek']??'';$selectedComfort=$_GET['comfort']??'';
?>
<section class="bg-ink py-14 text-white md:py-20"><div class="site-shell max-w-5xl"><p class="eyebrow text-emerald-200">Personal trip consultation</p><h1 class="mt-3 font-display text-5xl text-white md:text-7xl">Build my budget plan</h1><p class="mt-5 max-w-2xl text-lg leading-7 text-slate-300">Share what matters to you. We’ll use the details to design a realistic Himalayan journey—not a generic package.</p></div></section>
<section class="bg-mist py-12 md:py-20"><div class="site-shell max-w-5xl">
  <?php if(isset($_GET['success'])):?><div class="mb-8 border-l-4 border-pine bg-white p-6"><h2 class="font-display text-3xl text-ink">Your plan request is with us.</h2><p class="mt-2">Thank you. Tin-Tin Trekking will review your details and follow up using your preferred contact method.</p></div><?php endif;?>
  <?php if(isset($_GET['error'])):?><div class="mb-8 border-l-4 border-red-600 bg-white p-6 text-red-800">We couldn’t save your inquiry. Please check the database setup or contact us directly at <?= e(SITE['email']) ?>.</div><?php endif;?>
  <div id="budget-wizard" class="bg-white shadow-[0_20px_60px_rgba(16,42,67,.1)]">
    <div class="border-b p-6"><div class="mb-3 flex justify-between text-xs font-bold uppercase tracking-wider text-slate-500"><span id="step-label">Step 1 of 5</span><span>Your details stay private</span></div><div class="h-1 bg-slate-100"><div id="wizard-progress" class="h-full w-1/5 bg-pine transition-all"></div></div></div>
    <form action="<?= url('submit-inquiry.php') ?>" method="post" class="p-6 md:p-10"><input type="text" name="website_check" class="hidden" tabindex="-1" autocomplete="off"><input type="hidden" name="source" value="budget">
      <section class="wizard-step"><p class="eyebrow text-pine">01 — Trip</p><h2 class="mt-2 font-display text-4xl text-ink">Where might we take you?</h2><div class="mt-8 grid gap-5 md:grid-cols-2"><label class="md:col-span-2"><span class="mb-2 block text-sm font-bold">Trek, activity or region *</span><select name="trek" required class="form-field"><option value="">Select an option</option><?php if($selectedTrek!==''&&!in_array($selectedTrek,array_column($treks,'title'),true)):?><option selected><?= e($selectedTrek) ?></option><?php endif;?><option <?= $selectedTrek===''?'selected':'' ?>>Not sure — recommend something</option><?php foreach($treks as $t):?><option <?= $selectedTrek===$t['title']?'selected':'' ?>><?= e($t['title']) ?></option><?php endforeach;?><option>Nepal — another region</option><option>Bhutan</option><option>Tibet</option></select></label><label><span class="mb-2 block text-sm font-bold">Preferred month</span><input name="travel_month" type="month" class="form-field"></label><label><span class="mb-2 block text-sm font-bold">Exact dates, if known</span><input name="travel_dates" type="text" class="form-field" placeholder="e.g. 12–26 October"></label><label class="wizard-option"><input type="checkbox" name="flexible_dates" value="Yes"><span>My dates are flexible</span></label><label><span class="mb-2 block text-sm font-bold">Group size *</span><input name="group_size" type="number" min="1" max="50" required class="form-field" value="1"></label><label class="md:col-span-2"><span class="mb-2 block text-sm font-bold">Group type</span><select name="group_type" class="form-field"><option>Solo</option><option>Couple</option><option>Family</option><option>Friends</option><option>Private group</option></select></label></div><div class="mt-9 text-right"><button type="button" data-next class="btn-primary">Experience →</button></div></section>
      <section class="wizard-step hidden"><p class="eyebrow text-pine">02 — Experience</p><h2 class="mt-2 font-display text-4xl text-ink">Help us recommend the right pace.</h2><div class="mt-8 grid gap-5 md:grid-cols-3"><label><span class="mb-2 block text-sm font-bold">Trekking experience *</span><select name="trekking_experience" required class="form-field"><option value="">Choose</option><option>First trek</option><option>Some multi-day treks</option><option>Experienced trekker</option></select></label><label><span class="mb-2 block text-sm font-bold">Fitness level *</span><select name="fitness_level" required class="form-field"><option value="">Choose</option><option>Moderate activity</option><option>Regularly active</option><option>Very active</option></select></label><label><span class="mb-2 block text-sm font-bold">Altitude experience</span><select name="altitude_experience" class="form-field"><option>None</option><option>Up to 3,000 m</option><option>3,000–5,000 m</option><option>Above 5,000 m</option></select></label><label class="md:col-span-3"><span class="mb-2 block text-sm font-bold">Optional mobility, altitude or fitness note</span><textarea name="additional_health_notes" class="form-field" rows="4" placeholder="Share only what is useful for route planning. This does not replace medical advice."></textarea></label></div><div class="mt-9 flex justify-between"><button type="button" data-back class="font-bold text-pine">← Back</button><button type="button" data-next class="btn-primary">Comfort →</button></div></section>
      <section class="wizard-step hidden"><p class="eyebrow text-pine">03 — Comfort</p><h2 class="mt-2 font-display text-4xl text-ink">Where should comfort make a difference?</h2><div class="mt-8"><p class="mb-3 text-sm font-bold">On the trail *</p><div class="grid gap-3 md:grid-cols-3"><?php foreach(['Standard Teahouse'=>'standard','Comfort Lodge'=>'comfort','Luxury Lodge'=>'luxury'] as $label=>$value):?><label class="wizard-option"><input type="radio" name="accommodation" value="<?= $value ?>" required <?= $selectedComfort===$value?'checked':'' ?>><span><?= e($label) ?></span></label><?php endforeach;?></div><p class="mb-3 mt-7 text-sm font-bold">Kathmandu hotel</p><div class="grid gap-3 md:grid-cols-3"><?php foreach(['3-star','4-star','5-star'] as $o):?><label class="wizard-option"><input type="radio" name="hotel_level" value="<?= e($o) ?>"><span>Kathmandu <?= e($o) ?></span></label><?php endforeach;?></div><p class="mb-3 mt-7 text-sm font-bold">Room preference</p><div class="grid gap-3 md:grid-cols-2"><?php foreach(['Shared room','Private room'] as $o):?><label class="wizard-option"><input type="radio" name="room_type" value="<?= e($o) ?>"><span><?= e($o) ?></span></label><?php endforeach;?></div><p class="mb-3 mt-7 text-sm font-bold">Interests</p><div class="grid gap-3 sm:grid-cols-2 md:grid-cols-4"><?php foreach(['Culture','Photography','Wildlife','Food','Mountain views','Peak climbing','Relaxation'] as $o):?><label class="wizard-option"><input type="checkbox" name="interests[]" value="<?= e($o) ?>"><span><?= e($o) ?></span></label><?php endforeach;?></div></div><div class="mt-9 flex justify-between"><button type="button" data-back class="font-bold text-pine">← Back</button><button type="button" data-next class="btn-primary">Budget →</button></div></section>
      <section class="wizard-step hidden"><p class="eyebrow text-pine">04 — Budget</p><h2 class="mt-2 font-display text-4xl text-ink">What range should guide the plan?</h2><p class="mt-3 max-w-2xl leading-7">This private range helps us make useful choices. It is not a public package price or a commitment.</p><div class="mt-8 grid gap-3 md:grid-cols-2"><?php foreach(['Under $800','$800–$1,200','$1,200–$2,000','$2,000–$3,500','$3,500+','Not sure — advise me'] as $o):?><label class="wizard-option"><input type="radio" name="budget_range" value="<?= e($o) ?>" required><span><?= e($o) ?></span></label><?php endforeach;?></div><label class="mt-6 block"><span class="mb-2 block text-sm font-bold">Anything else we should know?</span><textarea name="additional_notes" class="form-field" rows="4"></textarea></label><div class="mt-9 flex justify-between"><button type="button" data-back class="font-bold text-pine">← Back</button><button type="button" data-next class="btn-primary">Contact →</button></div></section>
      <section class="wizard-step hidden"><p class="eyebrow text-pine">05 — Contact</p><h2 class="mt-2 font-display text-4xl text-ink">Where should we send your plan?</h2><div class="mt-8 grid gap-5 md:grid-cols-2"><label><span class="mb-2 block text-sm font-bold">Full name *</span><input name="full_name" required autocomplete="name" class="form-field"></label><label><span class="mb-2 block text-sm font-bold">Email *</span><input name="email" type="email" required autocomplete="email" class="form-field"></label><label><span class="mb-2 block text-sm font-bold">Phone</span><input name="phone" type="tel" autocomplete="tel" class="form-field"></label><label><span class="mb-2 block text-sm font-bold">WhatsApp</span><input name="whatsapp" type="tel" class="form-field"></label><label><span class="mb-2 block text-sm font-bold">Country *</span><input name="country" required autocomplete="country-name" class="form-field"></label><label><span class="mb-2 block text-sm font-bold">Preferred contact method</span><select name="preferred_contact" class="form-field"><option>Email</option><option>WhatsApp</option><option>Phone</option></select></label></div><p class="mt-6 text-xs leading-5 text-slate-500">By submitting, you ask Tin-Tin Trekking to contact you about this trip inquiry. Your details are used only for planning and communication.</p><div class="mt-9 flex items-center justify-between"><button type="button" data-back class="font-bold text-pine">← Back</button><button class="btn-primary" type="submit">Build My Budget Plan</button></div></section>
    </form>
  </div>
</div></section>
<?php require __DIR__.'/includes/footer.php';?>
